[options]
admin_passwd = $pbkdf2-sha512$600000$ee.9FyKEcO5dC8H4P4fQGg$5aF0IOy7n4rP6jKekJVFIxnQLG.jrg73r67BTx5RUKyVbdwBcZHrjPIlC.xdJ6rPH2/WlCYQiZxF0MvS5NTbMw
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_password
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo

